# Generated by Django 4.1.3 on 2022-11-26 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0003_remove_error_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='error',
            name='data',
            field=models.JSONField(default=[]),
        ),
    ]
